"""
Export Manager for FlowNotes
Supports multiple export formats: PDF, HTML, Anki, Obsidian
"""

import os
import re
from pathlib import Path
from typing import List, Dict, Optional
from datetime import datetime
import json

from utils.logger import get_logger

logger = get_logger(__name__)


class ExportManager:
    """Handles exporting notes to various formats"""

    def __init__(self, notes_dir: Path):
        """
        Initialize export manager

        Args:
            notes_dir: Base directory containing notes
        """
        self.notes_dir = Path(notes_dir)
        self.exports_dir = self.notes_dir / "exports"
        self.exports_dir.mkdir(exist_ok=True)

    def export_to_pdf(
        self,
        markdown_content: str,
        output_path: Optional[Path] = None,
        title: str = "FlowNotes Export",
        include_toc: bool = True
    ) -> Path:
        """
        Export markdown to PDF with styling

        Args:
            markdown_content: Markdown text to convert
            output_path: Optional custom output path
            title: Document title
            include_toc: Include table of contents

        Returns:
            Path to generated PDF file
        """
        try:
            import markdown2
            from weasyprint import HTML, CSS
            from weasyprint.text.fonts import FontConfiguration
        except ImportError as e:
            logger.error(f"PDF export requires weasyprint: {e}")
            raise ImportError("Install weasyprint: pip install weasyprint")

        logger.info(f"Generating PDF: {title}")

        # Convert markdown to HTML
        html_content = markdown2.markdown(
            markdown_content,
            extras=[
                "fenced-code-blocks",
                "tables",
                "header-ids",
                "toc" if include_toc else None,
                "code-friendly",
                "footnotes"
            ]
        )

        # Create styled HTML document
        full_html = self._create_pdf_html(html_content, title, include_toc)

        # Generate PDF
        if not output_path:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = self.exports_dir / f"{title.replace(' ', '_')}_{timestamp}.pdf"

        font_config = FontConfiguration()
        html_doc = HTML(string=full_html)
        css = CSS(string=self._get_pdf_css(), font_config=font_config)

        html_doc.write_pdf(output_path, stylesheets=[css], font_config=font_config)

        logger.info(f"PDF created: {output_path}")
        return output_path

    def _create_pdf_html(self, content: str, title: str, include_toc: bool) -> str:
        """Create full HTML document for PDF export"""
        toc_section = """
        <div class="toc">
            <h2>Table of Contents</h2>
            {{ toc }}
        </div>
        """ if include_toc else ""

        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>{title}</title>
        </head>
        <body>
            <div class="cover">
                <h1>{title}</h1>
                <p class="subtitle">Generated by FlowNotes</p>
                <p class="date">{datetime.now().strftime("%B %d, %Y")}</p>
            </div>
            {toc_section}
            <div class="content">
                {content}
            </div>
            <div class="footer">
                <p>Created with FlowNotes - AI-Powered Learning</p>
            </div>
        </body>
        </html>
        """

    def _get_pdf_css(self) -> str:
        """Get CSS styling for PDF export"""
        return """
        @page {
            size: A4;
            margin: 2cm;
            @bottom-right {
                content: "Page " counter(page) " of " counter(pages);
                font-size: 9pt;
                color: #666;
            }
        }

        body {
            font-family: 'Georgia', serif;
            font-size: 11pt;
            line-height: 1.6;
            color: #333;
        }

        .cover {
            page-break-after: always;
            text-align: center;
            padding-top: 30%;
        }

        .cover h1 {
            font-size: 32pt;
            color: #7C3AED;
            margin-bottom: 20pt;
        }

        .cover .subtitle {
            font-size: 14pt;
            color: #666;
        }

        .cover .date {
            font-size: 12pt;
            color: #999;
            margin-top: 10pt;
        }

        .toc {
            page-break-after: always;
        }

        h1, h2, h3, h4 {
            color: #7C3AED;
            page-break-after: avoid;
        }

        h1 { font-size: 24pt; margin-top: 24pt; }
        h2 { font-size: 18pt; margin-top: 18pt; }
        h3 { font-size: 14pt; margin-top: 14pt; }

        code {
            background-color: #f5f5f5;
            padding: 2px 4px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
            font-size: 9pt;
        }

        pre {
            background-color: #f5f5f5;
            padding: 12pt;
            border-left: 4px solid #7C3AED;
            border-radius: 4px;
            overflow-x: auto;
            page-break-inside: avoid;
        }

        pre code {
            background-color: transparent;
            padding: 0;
        }

        blockquote {
            border-left: 4px solid #EC4899;
            padding-left: 12pt;
            margin-left: 0;
            font-style: italic;
            color: #555;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 12pt 0;
            page-break-inside: avoid;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8pt;
            text-align: left;
        }

        th {
            background-color: #7C3AED;
            color: white;
        }

        .footer {
            margin-top: 40pt;
            padding-top: 12pt;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 9pt;
            color: #999;
        }
        """

    def export_to_html(
        self,
        markdown_content: str,
        output_path: Optional[Path] = None,
        title: str = "FlowNotes Export",
        standalone: bool = True
    ) -> Path:
        """
        Export markdown to styled HTML

        Args:
            markdown_content: Markdown text to convert
            output_path: Optional custom output path
            title: Document title
            standalone: Create standalone HTML file with CSS

        Returns:
            Path to generated HTML file
        """
        try:
            import markdown2
        except ImportError:
            logger.error("HTML export requires markdown2")
            raise ImportError("Install markdown2: pip install markdown2")

        logger.info(f"Generating HTML: {title}")

        # Convert markdown
        html_content = markdown2.markdown(
            markdown_content,
            extras=["fenced-code-blocks", "tables", "header-ids", "code-friendly"]
        )

        if standalone:
            html_content = self._create_standalone_html(html_content, title)

        # Save file
        if not output_path:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = self.exports_dir / f"{title.replace(' ', '_')}_{timestamp}.html"

        output_path.write_text(html_content, encoding='utf-8')

        logger.info(f"HTML created: {output_path}")
        return output_path

    def _create_standalone_html(self, content: str, title: str) -> str:
        """Create standalone HTML with embedded CSS"""
        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{title}</title>
            <style>
                body {{
                    max-width: 800px;
                    margin: 40px auto;
                    padding: 0 20px;
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                    line-height: 1.6;
                    color: #333;
                }}
                h1, h2, h3 {{ color: #7C3AED; }}
                code {{
                    background: #f5f5f5;
                    padding: 2px 6px;
                    border-radius: 3px;
                    font-family: 'Courier New', monospace;
                }}
                pre {{
                    background: #f5f5f5;
                    padding: 16px;
                    border-radius: 8px;
                    overflow-x: auto;
                }}
                pre code {{
                    background: transparent;
                    padding: 0;
                }}
                blockquote {{
                    border-left: 4px solid #EC4899;
                    padding-left: 16px;
                    margin-left: 0;
                    font-style: italic;
                }}
                table {{
                    width: 100%;
                    border-collapse: collapse;
                    margin: 20px 0;
                }}
                th, td {{
                    border: 1px solid #ddd;
                    padding: 12px;
                    text-align: left;
                }}
                th {{
                    background: #7C3AED;
                    color: white;
                }}
            </style>
        </head>
        <body>
            <h1>{title}</h1>
            <p style="color: #666; font-size: 0.9em;">Generated on {datetime.now().strftime("%B %d, %Y")}</p>
            <hr>
            {content}
        </body>
        </html>
        """

    def export_to_anki(
        self,
        flashcards: List[Dict[str, str]],
        deck_name: str = "FlowNotes",
        output_path: Optional[Path] = None
    ) -> Path:
        """
        Export flashcards to Anki package (.apkg)

        Args:
            flashcards: List of dicts with 'question' and 'answer' keys
            deck_name: Name of the Anki deck
            output_path: Optional custom output path

        Returns:
            Path to generated .apkg file
        """
        try:
            import genanki
        except ImportError:
            logger.error("Anki export requires genanki")
            raise ImportError("Install genanki: pip install genanki")

        logger.info(f"Creating Anki deck: {deck_name} ({len(flashcards)} cards)")

        # Create unique model ID based on deck name
        model_id = abs(hash(f"flownotes_{deck_name}")) % (10 ** 10)

        # Define note model
        model = genanki.Model(
            model_id,
            'FlowNotes Model',
            fields=[
                {'name': 'Question'},
                {'name': 'Answer'},
            ],
            templates=[
                {
                    'name': 'Card',
                    'qfmt': '<div style="font-size: 18px;">{{Question}}</div>',
                    'afmt': '''
                    <div style="font-size: 18px;">{{Question}}</div>
                    <hr>
                    <div style="font-size: 16px; color: #7C3AED;">{{Answer}}</div>
                    ''',
                },
            ],
            css="""
            .card {
                font-family: arial;
                font-size: 16px;
                text-align: center;
                color: black;
                background-color: white;
            }
            """
        )

        # Create deck
        deck_id = abs(hash(deck_name)) % (10 ** 10)
        deck = genanki.Deck(deck_id, deck_name)

        # Add cards
        for card in flashcards:
            note = genanki.Note(
                model=model,
                fields=[card.get('question', ''), card.get('answer', '')]
            )
            deck.add_note(note)

        # Save package
        if not output_path:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = self.exports_dir / f"{deck_name.replace(' ', '_')}_{timestamp}.apkg"

        genanki.Package(deck).write_to_file(str(output_path))

        logger.info(f"Anki package created: {output_path}")
        return output_path

    def export_to_obsidian(
        self,
        notes: List[Dict[str, any]],
        output_dir: Optional[Path] = None
    ) -> Path:
        """
        Export notes to Obsidian-compatible format with wikilinks

        Args:
            notes: List of note dicts with 'title', 'content', 'topic', 'tags'
            output_dir: Optional custom output directory

        Returns:
            Path to export directory
        """
        logger.info(f"Exporting {len(notes)} notes to Obsidian format")

        if not output_dir:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_dir = self.exports_dir / f"obsidian_export_{timestamp}"

        output_dir.mkdir(parents=True, exist_ok=True)

        for note in notes:
            # Convert note to Obsidian format
            content = self._convert_to_obsidian_format(note)

            # Save with safe filename
            safe_title = re.sub(r'[^\w\s-]', '', note.get('title', 'Untitled'))
            safe_title = safe_title.replace(' ', '_')
            file_path = output_dir / f"{safe_title}.md"

            file_path.write_text(content, encoding='utf-8')

        logger.info(f"Obsidian export created: {output_dir}")
        return output_dir

    def _convert_to_obsidian_format(self, note: Dict[str, any]) -> str:
        """Convert note to Obsidian markdown format"""
        title = note.get('title', 'Untitled')
        content = note.get('content', '')
        topic = note.get('topic', '')
        tags = note.get('tags', [])
        date = note.get('date', datetime.now().strftime("%Y-%m-%d"))

        # Convert tags to Obsidian format
        tag_line = ' '.join(f'#{tag}' for tag in tags) if tags else ''

        # Convert cross-references to wikilinks
        content = re.sub(
            r'\[([^\]]+)\]\(([^)]+)\.md\)',
            r'[[\2|\1]]',
            content
        )

        # Build Obsidian note
        obsidian_note = f"""---
title: {title}
date: {date}
topic: {topic}
tags: [{', '.join(tags)}]
---

# {title}

{tag_line}

{content}

---
*Created with FlowNotes*
"""
        return obsidian_note


# Example usage
if __name__ == "__main__":
    from pathlib import Path

    # Test export manager
    manager = ExportManager(Path.home() / "Projects" / "notes")

    # Test content
    test_markdown = """
# Neural Networks

## Introduction
Neural networks are computing systems inspired by biological neural networks.

## Key Concepts
- **Layers**: Input, Hidden, Output
- **Weights**: Adjusted during training
- **Activation Functions**: ReLU, Sigmoid, Tanh

## Code Example
```python
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
```

> **Note**: Backpropagation is fundamental to training
"""

    # Test PDF export
    print("Testing PDF export...")
    pdf_path = manager.export_to_pdf(test_markdown, title="Neural Networks Guide")
    print(f"PDF created: {pdf_path}")

    # Test HTML export
    print("\nTesting HTML export...")
    html_path = manager.export_to_html(test_markdown, title="Neural Networks Guide")
    print(f"HTML created: {html_path}")

    # Test Anki export
    print("\nTesting Anki export...")
    flashcards = [
        {"question": "What is a neural network?", "answer": "A computing system inspired by biological neural networks"},
        {"question": "Name 3 activation functions", "answer": "ReLU, Sigmoid, Tanh"}
    ]
    anki_path = manager.export_to_anki(flashcards, deck_name="Neural Networks")
    print(f"Anki package created: {anki_path}")
